language: objective-c
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
xcode_project: D2DEventCollectionKit/D2DEventCollectionKit.xcodeproj
xcode_scheme: D2DEventCollectionKitTests
branches:
  only:
  - develop
before_install:
	- brew update 
	- brew install xctool
 	- pod repo update