language: objective-c
xcode_sdk: iphonesimulator9.3
xcode_project: D2DEventCollectionKit/D2DEventCollectionKit.xcodeproj
xcode_scheme: D2DEventCollectionKitTests
before_install:
- brew update 
- brew install xctool
- pod repo update
branches:
  only:
  - develop