language: objective-c
xcode_sdk: iphonesimulator9.3
osx_image: xcode7.3
xcode_project: D2DEventCollectionKit/D2DEventCollectionKit.xcodeproj
xcode_scheme: D2DEventCollectionKitTests
branches:
  only:
  - develop
  script:
  - "./D2DEventCollectionKit/Scripts/test.sh"