language: objective-c
osx_image: xcode8
xcode_sdk: iphonesimulator10.0
xcode_project: D2DEventCollectionKit/D2DEventCollectionKit.xcodeproj
xcode_scheme: D2DEventCollectionKitTests
branches:
  only:
  - develop
before_install:
- brew update 
- brew install xctool
- pod repo update
